### PR TITLE
Make it work with Babel 7

### LINKED ISSUE #52: Babel 7 support
[Babel 7 is slowly rolling out](https://npm-stat.com/charts.html?package=babel-core&package=%40babel%2Fcore). At some point, it would be great to add support for it.

### PR DESCRIPTION
**Pull request by tleunen**
Fix #52 by changing `babel-register` with `@babel/register`

### CODE REVIEW

**Comment by tleunen** [comment]
I wonder if we should also explicitely add a peerDep on `@babel/core` 7 (or babel-core 7).

ping @kentcdodds @oliviertassinari

**Comment by kentcdodds** [comment]
Thanks @tleunen!

So actually, I'd prefer to go the route that babel-plugin-macros went which is that it doesn't require babel-register at all or even a specific version of babel: https://github.com/kentcdodds/babel-plugin-codegen/pull/12/files

It's a little large, but it basically amounts to passing the `babel` that our plugin function is called with and using that rather than any of the babel packages.

Would you be willing to do that?

**Comment by tleunen** [comment]
Yes, it's actually a better way to solve it. I'm doing that tomorrow.

**Comment by kentcdodds** [comment]
Super! Thank you very much :D

**Comment by tleunen** [comment]
@kentcdodds Could you take a look at why the tagged template tests fail? Looks like the tests don't use the babelrc config?

**Comment by kentcdodds** [comment]
I'll try to get to it as soon as I'm able. No promises I'll have time anytime soon though :-(

That said, at work we're upgrading to babel 7 so I may have some worktime for this.

**Comment by kentcdodds** [comment]
I'm working on this now and almost finished.

We're going to have a breaking change and lose support for something, but it'll be better this way.

**Comment by kentcdodds** [comment]
Alrighty, that should do it!

**Comment by tleunen** [comment]
Thank you @kentcdodds 😄

**Pull request merged**
