### PR TITLE
Fix broken links on table of content

### PR DESCRIPTION
**Pull request by PlayMa256**
**What**: Fix broken markdown on table of contents (link)

**Why**: Users can go directly to the topic when clicking on the table of content.

**How**: Updating markdown properly to have a link to the correct location.

### CODE REVIEW

**Comment by kentcdodds** [comment]
Hmmm... The table of contents is generated. If you look at this PR you'll see the diff isn't showing your ToC changes because when you commit, the table is regenerated based on the headings. I'm guessing we'll need to change a heading so it isn't broken.

**Comment by kentcdodds** [comment]
Looks like the fact that there's a link in the heading is the problem. If you move the link to right below the heading with something like "Learn more" then that would fix it.

**Comment by PlayMa256** [comment]
Oh... i did not pay attention to the regeneration of that... my bad. I'm going to rework that!

**Pull request merged**
