### PR TITLE
add typescript definition

### PR DESCRIPTION
**Pull request by xiaoxiangmoe**
**What**:

add typescript definition

**Why**:

use it in typescript

### CODE REVIEW

**Comment by xiaoxiangmoe** [comment]
@kentcdodds preval.require is not supported by macros.

**Comment by kentcdodds** [comment]
1. Yes it is
2. We'll need to do this in both packages

**Comment by xiaoxiangmoe** [comment]
2. We needn't write it in `babel-plugin-preval`.

we can't `import preval from 'babel-plugin-preval'` 

`typing` or `types` means add type definition to file of `main` field or `index.js`.

We add it in this package is a wrong behavior.

**Comment by kentcdodds** [comment]
> we can't import preval from 'babel-plugin-preval'

This is not correct. You can `import preval from 'babel-plugin-preval/macro'`

**Comment by xiaoxiangmoe** [comment]
> This is not correct. You can `import preval from 'babel-plugin-preval/macro'`

So we should has a `macro.d.ts` file in package root like `macro.js`.

you needn't write `macro.js` in `package.json`. `macro.d.ts` is the same.

**Comment by kentcdodds** [comment]
Dude, believe me, I know what I'm talking about. Both of the things I mentioned in my original comment need to happen. I will not merge until they do.

**Comment by xiaoxiangmoe** [comment]
see:  [How TypeScript resolves modules](https://www.typescriptlang.org/docs/handbook/module-resolution.html#how-typescript-resolves-modules)

Dude, believe me, if you like to add types field, you can move `macro.js` into `macro/index.js`,touch `macro/index.d.ts` touch `macro/package.json` and add main field and types field in `macro/package.json`.

**Comment by kentcdodds** [comment]
I'm sorry, but if this is the way you're going to behave on this project, I don't want to work with you.

Neither of your PRs will include the types in the published package due to missing `files` additions. I've asked you to do it multiple times and you wont do it.

Someone else can feel free to contribute the types, or you can put it on DefinitelyTyped, but I'm not going to collaborate with you on this project.

**Comment by xiaoxiangmoe** [comment]
I am sorry that I offended you.
But I don't think there is any error in my code. 

You didn't give me a reasonable explanation why we need to provide the types property in this project.
You just think that I am wrong and don't give me a reasonable explanation.
And I am constantly explaining my thoughts to you. 

I don't think close issue is a good solution to this problem.

**Pull request closed without merging**
