### PR TITLE
docs: add React doc generation example

### PR DESCRIPTION
**Pull request by souporserious**
**What**:
Add example showing how to generate React documentation.

**Why**:
You asked in this [tweet](https://twitter.com/kentcdodds/status/886927259667451904) :)

**How**:
Added a link to a gist for now.

### CODE REVIEW

**Comment by kentcdodds** [comment]
Would you like to [add yourself](../blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor) to the [contributors table](../#contributors)? You can make another PR to add yourself as an example contributor 😄 It's a very valuable contribution :clap:

**Comment by souporserious** [comment]
If you think so 😇 I don't feel worthy enough to be up there for just an example haha

**Comment by kentcdodds** [comment]
Oh dude, there are 438 people who've starred this repo and very few who have done anything let alone improve docs for everyone else. You're totally "worthy" :smile: Thanks!

**Comment by souporserious** [comment]
I appreciate it 😊 I'll add another PR with an icon example and then add myself 🙃

**Pull request merged**
